name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_USERNAME: slavka886

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/myapp-frontend:latest ./FrontForProject
          docker push ${{ env.DOCKER_USERNAME }}/myapp-frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/myapp-backend:latest ./ServerForProject/server
          docker push ${{ env.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Build and Push Database
        run: |
          docker build -f DockerfileDB -t ${{ env.DOCKER_USERNAME }}/myapp-sqlite:latest ./ServerForProject/server
          docker push ${{ env.DOCKER_USERNAME }}/myapp-sqlite:latest

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/myapp
            docker stack deploy -c docker-swarm.yml myapp --with-registry-auth