name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_USERNAME: slavka886

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Backend with Maven
        working-directory: ./ServerForProject/server
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/myapp-frontend:latest ./FrontForProject
          docker push ${{ env.DOCKER_USERNAME }}/myapp-frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/myapp-backend:latest ./ServerForProject/server
          docker push ${{ env.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Build and Push Database
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/myapp-sqlite:latest ./ServerForProject/server
          docker push ${{ env.DOCKER_USERNAME }}/myapp-sqlite:latest